apiVersion: postgres.rijojohn.xyz/v1alpha1
kind: PostgresTenant
metadata:
  labels:
    app.kubernetes.io/name: fleetdb
    app.kubernetes.io/managed-by: kustomize
  name: postgrestenant-sample
spec:
  # TODO(user): Add fields here
